### ISSUE TITLE
Badge Color Feedback

### ISSUE THREAD

**Issue by vsoch** [vsoch/mkdocs-jekyll#9]
![image](https://user-images.githubusercontent.com/814322/60386723-02281100-9a67-11e9-8226-b967445f9941.png)

And here are the current colors / styling:

```css
span.badge {
  font-family: "Open Sans", sans-serif;
  padding: 2px 5px;
  margin-right: 5px;
  text-transform: uppercase;
  font-size: 1.0rem;
  border-radius: 2px;
  background: #eee;
  font-weight: bold; }
span.badge-primary {
  background: #3c7dae;
  color: #fff; }
span.badge-secondary {
  background: #999;
  color: #fff; }
span.badge-danger {
  background: firebrick;
  color: #fff; }
span.badge-warning {
  background: darkorange;
  color: #fff; }
span.badge-info {
  background: royalblue;
  color: #fff; }
span.badge-success {
  background: forestgreen;
  color: #fff; }
```
